In [2]:
import cv2
image = cv2.imread('./images/goldengate.jpg')

print(image)

[[[164 195 192]
  [164 195 192]
  [165 196 193]
  ...
  [ 35  21  33]
  [ 35  21  33]
  [ 34  20  32]]

 [[164 195 192]
  [165 196 193]
  [165 196 193]
  ...
  [ 35  21  33]
  [ 35  21  33]
  [ 34  20  32]]

 [[164 195 194]
  [165 196 195]
  [165 196 195]
  ...
  [ 35  21  33]
  [ 35  21  33]
  [ 34  20  32]]

 ...

 [[ 29  51  69]
  [ 27  49  67]
  [ 25  47  65]
  ...
  [  6  21  37]
  [  5  21  34]
  [  5  21  34]]

 [[ 28  50  68]
  [ 27  49  67]
  [ 25  47  65]
  ...
  [  5  21  34]
  [  6  22  35]
  [  4  20  33]]

 [[ 26  48  66]
  [ 25  47  65]
  [ 23  45  63]
  ...
  [  4  20  33]
  [  7  23  36]
  [  4  20  32]]]


In [3]:
#show an image
cv2.imshow('output', image)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
#color conversion

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow('output', gray)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
# Create a blank image
import numpy as np

image = np.zeros((100, 100)) # 100 rows, 100 cols
cv2.imshow('output', image)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
# Checking the value of each pixel

for row in range(50):
    for col in range(50):
        print("Row : ",row,"Col :", col)
        print(image[row][col])


Row :  0 Col : 0
0.0
Row :  0 Col : 1
0.0
Row :  0 Col : 2
0.0
Row :  0 Col : 3
0.0
Row :  0 Col : 4
0.0
Row :  0 Col : 5
0.0
Row :  0 Col : 6
0.0
Row :  0 Col : 7
0.0
Row :  0 Col : 8
0.0
Row :  0 Col : 9
0.0
Row :  0 Col : 10
0.0
Row :  0 Col : 11
0.0
Row :  0 Col : 12
0.0
Row :  0 Col : 13
0.0
Row :  0 Col : 14
0.0
Row :  0 Col : 15
0.0
Row :  0 Col : 16
0.0
Row :  0 Col : 17
0.0
Row :  0 Col : 18
0.0
Row :  0 Col : 19
0.0
Row :  0 Col : 20
0.0
Row :  0 Col : 21
0.0
Row :  0 Col : 22
0.0
Row :  0 Col : 23
0.0
Row :  0 Col : 24
0.0
Row :  0 Col : 25
0.0
Row :  0 Col : 26
0.0
Row :  0 Col : 27
0.0
Row :  0 Col : 28
0.0
Row :  0 Col : 29
0.0
Row :  0 Col : 30
0.0
Row :  0 Col : 31
0.0
Row :  0 Col : 32
0.0
Row :  0 Col : 33
0.0
Row :  0 Col : 34
0.0
Row :  0 Col : 35
0.0
Row :  0 Col : 36
0.0
Row :  0 Col : 37
0.0
Row :  0 Col : 38
0.0
Row :  0 Col : 39
0.0
Row :  0 Col : 40
0.0
Row :  0 Col : 41
0.0
Row :  0 Col : 42
0.0
Row :  0 Col : 43
0.0
Row :  0 Col : 44
0.0
Row :  0 Col : 45
0.

Row :  14 Col : 9
0.0
Row :  14 Col : 10
0.0
Row :  14 Col : 11
0.0
Row :  14 Col : 12
0.0
Row :  14 Col : 13
0.0
Row :  14 Col : 14
0.0
Row :  14 Col : 15
0.0
Row :  14 Col : 16
0.0
Row :  14 Col : 17
0.0
Row :  14 Col : 18
0.0
Row :  14 Col : 19
0.0
Row :  14 Col : 20
0.0
Row :  14 Col : 21
0.0
Row :  14 Col : 22
0.0
Row :  14 Col : 23
0.0
Row :  14 Col : 24
0.0
Row :  14 Col : 25
0.0
Row :  14 Col : 26
0.0
Row :  14 Col : 27
0.0
Row :  14 Col : 28
0.0
Row :  14 Col : 29
0.0
Row :  14 Col : 30
0.0
Row :  14 Col : 31
0.0
Row :  14 Col : 32
0.0
Row :  14 Col : 33
0.0
Row :  14 Col : 34
0.0
Row :  14 Col : 35
0.0
Row :  14 Col : 36
0.0
Row :  14 Col : 37
0.0
Row :  14 Col : 38
0.0
Row :  14 Col : 39
0.0
Row :  14 Col : 40
0.0
Row :  14 Col : 41
0.0
Row :  14 Col : 42
0.0
Row :  14 Col : 43
0.0
Row :  14 Col : 44
0.0
Row :  14 Col : 45
0.0
Row :  14 Col : 46
0.0
Row :  14 Col : 47
0.0
Row :  14 Col : 48
0.0
Row :  14 Col : 49
0.0
Row :  15 Col : 0
0.0
Row :  15 Col : 1
0.0
Row :  15 Col 

Row :  22 Col : 21
0.0
Row :  22 Col : 22
0.0
Row :  22 Col : 23
0.0
Row :  22 Col : 24
0.0
Row :  22 Col : 25
0.0
Row :  22 Col : 26
0.0
Row :  22 Col : 27
0.0
Row :  22 Col : 28
0.0
Row :  22 Col : 29
0.0
Row :  22 Col : 30
0.0
Row :  22 Col : 31
0.0
Row :  22 Col : 32
0.0
Row :  22 Col : 33
0.0
Row :  22 Col : 34
0.0
Row :  22 Col : 35
0.0
Row :  22 Col : 36
0.0
Row :  22 Col : 37
0.0
Row :  22 Col : 38
0.0
Row :  22 Col : 39
0.0
Row :  22 Col : 40
0.0
Row :  22 Col : 41
0.0
Row :  22 Col : 42
0.0
Row :  22 Col : 43
0.0
Row :  22 Col : 44
0.0
Row :  22 Col : 45
0.0
Row :  22 Col : 46
0.0
Row :  22 Col : 47
0.0
Row :  22 Col : 48
0.0
Row :  22 Col : 49
0.0
Row :  23 Col : 0
0.0
Row :  23 Col : 1
0.0
Row :  23 Col : 2
0.0
Row :  23 Col : 3
0.0
Row :  23 Col : 4
0.0
Row :  23 Col : 5
0.0
Row :  23 Col : 6
0.0
Row :  23 Col : 7
0.0
Row :  23 Col : 8
0.0
Row :  23 Col : 9
0.0
Row :  23 Col : 10
0.0
Row :  23 Col : 11
0.0
Row :  23 Col : 12
0.0
Row :  23 Col : 13
0.0
Row :  23 Col : 14
0.

Row :  29 Col : 42
0.0
Row :  29 Col : 43
0.0
Row :  29 Col : 44
0.0
Row :  29 Col : 45
0.0
Row :  29 Col : 46
0.0
Row :  29 Col : 47
0.0
Row :  29 Col : 48
0.0
Row :  29 Col : 49
0.0
Row :  30 Col : 0
0.0
Row :  30 Col : 1
0.0
Row :  30 Col : 2
0.0
Row :  30 Col : 3
0.0
Row :  30 Col : 4
0.0
Row :  30 Col : 5
0.0
Row :  30 Col : 6
0.0
Row :  30 Col : 7
0.0
Row :  30 Col : 8
0.0
Row :  30 Col : 9
0.0
Row :  30 Col : 10
0.0
Row :  30 Col : 11
0.0
Row :  30 Col : 12
0.0
Row :  30 Col : 13
0.0
Row :  30 Col : 14
0.0
Row :  30 Col : 15
0.0
Row :  30 Col : 16
0.0
Row :  30 Col : 17
0.0
Row :  30 Col : 18
0.0
Row :  30 Col : 19
0.0
Row :  30 Col : 20
0.0
Row :  30 Col : 21
0.0
Row :  30 Col : 22
0.0
Row :  30 Col : 23
0.0
Row :  30 Col : 24
0.0
Row :  30 Col : 25
0.0
Row :  30 Col : 26
0.0
Row :  30 Col : 27
0.0
Row :  30 Col : 28
0.0
Row :  30 Col : 29
0.0
Row :  30 Col : 30
0.0
Row :  30 Col : 31
0.0
Row :  30 Col : 32
0.0
Row :  30 Col : 33
0.0
Row :  30 Col : 34
0.0
Row :  30 Col : 35
0.

Row :  37 Col : 24
0.0
Row :  37 Col : 25
0.0
Row :  37 Col : 26
0.0
Row :  37 Col : 27
0.0
Row :  37 Col : 28
0.0
Row :  37 Col : 29
0.0
Row :  37 Col : 30
0.0
Row :  37 Col : 31
0.0
Row :  37 Col : 32
0.0
Row :  37 Col : 33
0.0
Row :  37 Col : 34
0.0
Row :  37 Col : 35
0.0
Row :  37 Col : 36
0.0
Row :  37 Col : 37
0.0
Row :  37 Col : 38
0.0
Row :  37 Col : 39
0.0
Row :  37 Col : 40
0.0
Row :  37 Col : 41
0.0
Row :  37 Col : 42
0.0
Row :  37 Col : 43
0.0
Row :  37 Col : 44
0.0
Row :  37 Col : 45
0.0
Row :  37 Col : 46
0.0
Row :  37 Col : 47
0.0
Row :  37 Col : 48
0.0
Row :  37 Col : 49
0.0
Row :  38 Col : 0
0.0
Row :  38 Col : 1
0.0
Row :  38 Col : 2
0.0
Row :  38 Col : 3
0.0
Row :  38 Col : 4
0.0
Row :  38 Col : 5
0.0
Row :  38 Col : 6
0.0
Row :  38 Col : 7
0.0
Row :  38 Col : 8
0.0
Row :  38 Col : 9
0.0
Row :  38 Col : 10
0.0
Row :  38 Col : 11
0.0
Row :  38 Col : 12
0.0
Row :  38 Col : 13
0.0
Row :  38 Col : 14
0.0
Row :  38 Col : 15
0.0
Row :  38 Col : 16
0.0
Row :  38 Col : 17
0.

0.0
Row :  46 Col : 4
0.0
Row :  46 Col : 5
0.0
Row :  46 Col : 6
0.0
Row :  46 Col : 7
0.0
Row :  46 Col : 8
0.0
Row :  46 Col : 9
0.0
Row :  46 Col : 10
0.0
Row :  46 Col : 11
0.0
Row :  46 Col : 12
0.0
Row :  46 Col : 13
0.0
Row :  46 Col : 14
0.0
Row :  46 Col : 15
0.0
Row :  46 Col : 16
0.0
Row :  46 Col : 17
0.0
Row :  46 Col : 18
0.0
Row :  46 Col : 19
0.0
Row :  46 Col : 20
0.0
Row :  46 Col : 21
0.0
Row :  46 Col : 22
0.0
Row :  46 Col : 23
0.0
Row :  46 Col : 24
0.0
Row :  46 Col : 25
0.0
Row :  46 Col : 26
0.0
Row :  46 Col : 27
0.0
Row :  46 Col : 28
0.0
Row :  46 Col : 29
0.0
Row :  46 Col : 30
0.0
Row :  46 Col : 31
0.0
Row :  46 Col : 32
0.0
Row :  46 Col : 33
0.0
Row :  46 Col : 34
0.0
Row :  46 Col : 35
0.0
Row :  46 Col : 36
0.0
Row :  46 Col : 37
0.0
Row :  46 Col : 38
0.0
Row :  46 Col : 39
0.0
Row :  46 Col : 40
0.0
Row :  46 Col : 41
0.0
Row :  46 Col : 42
0.0
Row :  46 Col : 43
0.0
Row :  46 Col : 44
0.0
Row :  46 Col : 45
0.0
Row :  46 Col : 46
0.0
Row :  46 Col

In [29]:
#changing the value of each pixel
import random

#help(random.randint)

for row in range(100):
    for col in range(100):
        print("Row : ",row,"Col :", col)
        image[row][col] = int(random.randint(100,240))
        print(image[row][col])

Row :  0 Col : 0
117.0
Row :  0 Col : 1
117.0
Row :  0 Col : 2
126.0
Row :  0 Col : 3
107.0
Row :  0 Col : 4
153.0
Row :  0 Col : 5
147.0
Row :  0 Col : 6
229.0
Row :  0 Col : 7
112.0
Row :  0 Col : 8
183.0
Row :  0 Col : 9
190.0
Row :  0 Col : 10
142.0
Row :  0 Col : 11
103.0
Row :  0 Col : 12
229.0
Row :  0 Col : 13
192.0
Row :  0 Col : 14
142.0
Row :  0 Col : 15
169.0
Row :  0 Col : 16
128.0
Row :  0 Col : 17
223.0
Row :  0 Col : 18
117.0
Row :  0 Col : 19
126.0
Row :  0 Col : 20
112.0
Row :  0 Col : 21
154.0
Row :  0 Col : 22
164.0
Row :  0 Col : 23
149.0
Row :  0 Col : 24
215.0
Row :  0 Col : 25
124.0
Row :  0 Col : 26
220.0
Row :  0 Col : 27
219.0
Row :  0 Col : 28
235.0
Row :  0 Col : 29
117.0
Row :  0 Col : 30
121.0
Row :  0 Col : 31
104.0
Row :  0 Col : 32
182.0
Row :  0 Col : 33
239.0
Row :  0 Col : 34
177.0
Row :  0 Col : 35
202.0
Row :  0 Col : 36
130.0
Row :  0 Col : 37
125.0
Row :  0 Col : 38
221.0
Row :  0 Col : 39
130.0
Row :  0 Col : 40
212.0
Row :  0 Col : 41
225.0
Ro

Row :  6 Col : 71
199.0
Row :  6 Col : 72
237.0
Row :  6 Col : 73
152.0
Row :  6 Col : 74
229.0
Row :  6 Col : 75
219.0
Row :  6 Col : 76
193.0
Row :  6 Col : 77
222.0
Row :  6 Col : 78
125.0
Row :  6 Col : 79
106.0
Row :  6 Col : 80
157.0
Row :  6 Col : 81
138.0
Row :  6 Col : 82
163.0
Row :  6 Col : 83
223.0
Row :  6 Col : 84
208.0
Row :  6 Col : 85
238.0
Row :  6 Col : 86
124.0
Row :  6 Col : 87
185.0
Row :  6 Col : 88
115.0
Row :  6 Col : 89
161.0
Row :  6 Col : 90
123.0
Row :  6 Col : 91
226.0
Row :  6 Col : 92
116.0
Row :  6 Col : 93
172.0
Row :  6 Col : 94
147.0
Row :  6 Col : 95
177.0
Row :  6 Col : 96
203.0
Row :  6 Col : 97
131.0
Row :  6 Col : 98
112.0
Row :  6 Col : 99
113.0
Row :  7 Col : 0
122.0
Row :  7 Col : 1
154.0
Row :  7 Col : 2
235.0
Row :  7 Col : 3
220.0
Row :  7 Col : 4
117.0
Row :  7 Col : 5
166.0
Row :  7 Col : 6
195.0
Row :  7 Col : 7
125.0
Row :  7 Col : 8
124.0
Row :  7 Col : 9
105.0
Row :  7 Col : 10
102.0
Row :  7 Col : 11
140.0
Row :  7 Col : 12
188.0
Ro

Row :  13 Col : 40
118.0
Row :  13 Col : 41
204.0
Row :  13 Col : 42
224.0
Row :  13 Col : 43
194.0
Row :  13 Col : 44
160.0
Row :  13 Col : 45
131.0
Row :  13 Col : 46
234.0
Row :  13 Col : 47
133.0
Row :  13 Col : 48
143.0
Row :  13 Col : 49
204.0
Row :  13 Col : 50
206.0
Row :  13 Col : 51
121.0
Row :  13 Col : 52
135.0
Row :  13 Col : 53
221.0
Row :  13 Col : 54
197.0
Row :  13 Col : 55
178.0
Row :  13 Col : 56
222.0
Row :  13 Col : 57
225.0
Row :  13 Col : 58
132.0
Row :  13 Col : 59
173.0
Row :  13 Col : 60
104.0
Row :  13 Col : 61
142.0
Row :  13 Col : 62
146.0
Row :  13 Col : 63
227.0
Row :  13 Col : 64
169.0
Row :  13 Col : 65
232.0
Row :  13 Col : 66
208.0
Row :  13 Col : 67
167.0
Row :  13 Col : 68
194.0
Row :  13 Col : 69
128.0
Row :  13 Col : 70
222.0
Row :  13 Col : 71
125.0
Row :  13 Col : 72
231.0
Row :  13 Col : 73
118.0
Row :  13 Col : 74
108.0
Row :  13 Col : 75
152.0
Row :  13 Col : 76
217.0
Row :  13 Col : 77
164.0
Row :  13 Col : 78
226.0
Row :  13 Col : 79
131.0


Row :  17 Col : 38
123.0
Row :  17 Col : 39
223.0
Row :  17 Col : 40
221.0
Row :  17 Col : 41
160.0
Row :  17 Col : 42
152.0
Row :  17 Col : 43
157.0
Row :  17 Col : 44
127.0
Row :  17 Col : 45
121.0
Row :  17 Col : 46
193.0
Row :  17 Col : 47
151.0
Row :  17 Col : 48
228.0
Row :  17 Col : 49
185.0
Row :  17 Col : 50
141.0
Row :  17 Col : 51
187.0
Row :  17 Col : 52
180.0
Row :  17 Col : 53
204.0
Row :  17 Col : 54
201.0
Row :  17 Col : 55
180.0
Row :  17 Col : 56
185.0
Row :  17 Col : 57
118.0
Row :  17 Col : 58
207.0
Row :  17 Col : 59
214.0
Row :  17 Col : 60
164.0
Row :  17 Col : 61
105.0
Row :  17 Col : 62
204.0
Row :  17 Col : 63
233.0
Row :  17 Col : 64
133.0
Row :  17 Col : 65
238.0
Row :  17 Col : 66
163.0
Row :  17 Col : 67
216.0
Row :  17 Col : 68
197.0
Row :  17 Col : 69
145.0
Row :  17 Col : 70
117.0
Row :  17 Col : 71
161.0
Row :  17 Col : 72
149.0
Row :  17 Col : 73
112.0
Row :  17 Col : 74
129.0
Row :  17 Col : 75
100.0
Row :  17 Col : 76
165.0
Row :  17 Col : 77
139.0


Row :  21 Col : 38
131.0
Row :  21 Col : 39
193.0
Row :  21 Col : 40
173.0
Row :  21 Col : 41
228.0
Row :  21 Col : 42
172.0
Row :  21 Col : 43
206.0
Row :  21 Col : 44
165.0
Row :  21 Col : 45
162.0
Row :  21 Col : 46
138.0
Row :  21 Col : 47
171.0
Row :  21 Col : 48
104.0
Row :  21 Col : 49
216.0
Row :  21 Col : 50
168.0
Row :  21 Col : 51
202.0
Row :  21 Col : 52
142.0
Row :  21 Col : 53
107.0
Row :  21 Col : 54
104.0
Row :  21 Col : 55
228.0
Row :  21 Col : 56
240.0
Row :  21 Col : 57
236.0
Row :  21 Col : 58
195.0
Row :  21 Col : 59
137.0
Row :  21 Col : 60
111.0
Row :  21 Col : 61
173.0
Row :  21 Col : 62
121.0
Row :  21 Col : 63
104.0
Row :  21 Col : 64
182.0
Row :  21 Col : 65
238.0
Row :  21 Col : 66
120.0
Row :  21 Col : 67
212.0
Row :  21 Col : 68
192.0
Row :  21 Col : 69
141.0
Row :  21 Col : 70
167.0
Row :  21 Col : 71
200.0
Row :  21 Col : 72
165.0
Row :  21 Col : 73
174.0
Row :  21 Col : 74
112.0
Row :  21 Col : 75
238.0
Row :  21 Col : 76
204.0
Row :  21 Col : 77
160.0


Row :  25 Col : 45
191.0
Row :  25 Col : 46
177.0
Row :  25 Col : 47
165.0
Row :  25 Col : 48
140.0
Row :  25 Col : 49
192.0
Row :  25 Col : 50
193.0
Row :  25 Col : 51
239.0
Row :  25 Col : 52
115.0
Row :  25 Col : 53
178.0
Row :  25 Col : 54
239.0
Row :  25 Col : 55
113.0
Row :  25 Col : 56
102.0
Row :  25 Col : 57
224.0
Row :  25 Col : 58
130.0
Row :  25 Col : 59
177.0
Row :  25 Col : 60
234.0
Row :  25 Col : 61
130.0
Row :  25 Col : 62
239.0
Row :  25 Col : 63
163.0
Row :  25 Col : 64
117.0
Row :  25 Col : 65
188.0
Row :  25 Col : 66
116.0
Row :  25 Col : 67
201.0
Row :  25 Col : 68
168.0
Row :  25 Col : 69
174.0
Row :  25 Col : 70
213.0
Row :  25 Col : 71
206.0
Row :  25 Col : 72
222.0
Row :  25 Col : 73
220.0
Row :  25 Col : 74
181.0
Row :  25 Col : 75
134.0
Row :  25 Col : 76
211.0
Row :  25 Col : 77
136.0
Row :  25 Col : 78
218.0
Row :  25 Col : 79
106.0
Row :  25 Col : 80
112.0
Row :  25 Col : 81
203.0
Row :  25 Col : 82
144.0
Row :  25 Col : 83
153.0
Row :  25 Col : 84
192.0


Row :  29 Col : 38
159.0
Row :  29 Col : 39
197.0
Row :  29 Col : 40
233.0
Row :  29 Col : 41
204.0
Row :  29 Col : 42
112.0
Row :  29 Col : 43
186.0
Row :  29 Col : 44
174.0
Row :  29 Col : 45
200.0
Row :  29 Col : 46
225.0
Row :  29 Col : 47
196.0
Row :  29 Col : 48
150.0
Row :  29 Col : 49
134.0
Row :  29 Col : 50
127.0
Row :  29 Col : 51
113.0
Row :  29 Col : 52
237.0
Row :  29 Col : 53
239.0
Row :  29 Col : 54
224.0
Row :  29 Col : 55
209.0
Row :  29 Col : 56
110.0
Row :  29 Col : 57
164.0
Row :  29 Col : 58
184.0
Row :  29 Col : 59
239.0
Row :  29 Col : 60
198.0
Row :  29 Col : 61
235.0
Row :  29 Col : 62
233.0
Row :  29 Col : 63
153.0
Row :  29 Col : 64
184.0
Row :  29 Col : 65
158.0
Row :  29 Col : 66
176.0
Row :  29 Col : 67
152.0
Row :  29 Col : 68
145.0
Row :  29 Col : 69
197.0
Row :  29 Col : 70
236.0
Row :  29 Col : 71
178.0
Row :  29 Col : 72
102.0
Row :  29 Col : 73
104.0
Row :  29 Col : 74
214.0
Row :  29 Col : 75
220.0
Row :  29 Col : 76
187.0
Row :  29 Col : 77
198.0


Row :  34 Col : 38
190.0
Row :  34 Col : 39
224.0
Row :  34 Col : 40
228.0
Row :  34 Col : 41
221.0
Row :  34 Col : 42
130.0
Row :  34 Col : 43
198.0
Row :  34 Col : 44
141.0
Row :  34 Col : 45
206.0
Row :  34 Col : 46
192.0
Row :  34 Col : 47
210.0
Row :  34 Col : 48
126.0
Row :  34 Col : 49
216.0
Row :  34 Col : 50
100.0
Row :  34 Col : 51
123.0
Row :  34 Col : 52
226.0
Row :  34 Col : 53
215.0
Row :  34 Col : 54
174.0
Row :  34 Col : 55
166.0
Row :  34 Col : 56
143.0
Row :  34 Col : 57
101.0
Row :  34 Col : 58
130.0
Row :  34 Col : 59
162.0
Row :  34 Col : 60
102.0
Row :  34 Col : 61
218.0
Row :  34 Col : 62
213.0
Row :  34 Col : 63
134.0
Row :  34 Col : 64
100.0
Row :  34 Col : 65
178.0
Row :  34 Col : 66
164.0
Row :  34 Col : 67
188.0
Row :  34 Col : 68
146.0
Row :  34 Col : 69
175.0
Row :  34 Col : 70
102.0
Row :  34 Col : 71
194.0
Row :  34 Col : 72
110.0
Row :  34 Col : 73
182.0
Row :  34 Col : 74
149.0
Row :  34 Col : 75
133.0
Row :  34 Col : 76
169.0
Row :  34 Col : 77
100.0


Row :  38 Col : 34
132.0
Row :  38 Col : 35
236.0
Row :  38 Col : 36
215.0
Row :  38 Col : 37
233.0
Row :  38 Col : 38
226.0
Row :  38 Col : 39
211.0
Row :  38 Col : 40
104.0
Row :  38 Col : 41
150.0
Row :  38 Col : 42
156.0
Row :  38 Col : 43
154.0
Row :  38 Col : 44
231.0
Row :  38 Col : 45
184.0
Row :  38 Col : 46
221.0
Row :  38 Col : 47
149.0
Row :  38 Col : 48
100.0
Row :  38 Col : 49
126.0
Row :  38 Col : 50
200.0
Row :  38 Col : 51
210.0
Row :  38 Col : 52
158.0
Row :  38 Col : 53
138.0
Row :  38 Col : 54
102.0
Row :  38 Col : 55
156.0
Row :  38 Col : 56
198.0
Row :  38 Col : 57
210.0
Row :  38 Col : 58
224.0
Row :  38 Col : 59
132.0
Row :  38 Col : 60
202.0
Row :  38 Col : 61
163.0
Row :  38 Col : 62
141.0
Row :  38 Col : 63
214.0
Row :  38 Col : 64
230.0
Row :  38 Col : 65
100.0
Row :  38 Col : 66
149.0
Row :  38 Col : 67
212.0
Row :  38 Col : 68
204.0
Row :  38 Col : 69
217.0
Row :  38 Col : 70
117.0
Row :  38 Col : 71
121.0
Row :  38 Col : 72
172.0
Row :  38 Col : 73
230.0


Row :  43 Col : 42
240.0
Row :  43 Col : 43
110.0
Row :  43 Col : 44
121.0
Row :  43 Col : 45
230.0
Row :  43 Col : 46
172.0
Row :  43 Col : 47
115.0
Row :  43 Col : 48
160.0
Row :  43 Col : 49
179.0
Row :  43 Col : 50
118.0
Row :  43 Col : 51
211.0
Row :  43 Col : 52
208.0
Row :  43 Col : 53
116.0
Row :  43 Col : 54
192.0
Row :  43 Col : 55
223.0
Row :  43 Col : 56
109.0
Row :  43 Col : 57
188.0
Row :  43 Col : 58
116.0
Row :  43 Col : 59
120.0
Row :  43 Col : 60
103.0
Row :  43 Col : 61
224.0
Row :  43 Col : 62
231.0
Row :  43 Col : 63
205.0
Row :  43 Col : 64
129.0
Row :  43 Col : 65
215.0
Row :  43 Col : 66
105.0
Row :  43 Col : 67
109.0
Row :  43 Col : 68
122.0
Row :  43 Col : 69
176.0
Row :  43 Col : 70
114.0
Row :  43 Col : 71
236.0
Row :  43 Col : 72
145.0
Row :  43 Col : 73
102.0
Row :  43 Col : 74
173.0
Row :  43 Col : 75
175.0
Row :  43 Col : 76
235.0
Row :  43 Col : 77
146.0
Row :  43 Col : 78
186.0
Row :  43 Col : 79
236.0
Row :  43 Col : 80
143.0
Row :  43 Col : 81
185.0


Row :  46 Col : 94
149.0
Row :  46 Col : 95
149.0
Row :  46 Col : 96
114.0
Row :  46 Col : 97
122.0
Row :  46 Col : 98
195.0
Row :  46 Col : 99
208.0
Row :  47 Col : 0
130.0
Row :  47 Col : 1
204.0
Row :  47 Col : 2
216.0
Row :  47 Col : 3
129.0
Row :  47 Col : 4
109.0
Row :  47 Col : 5
186.0
Row :  47 Col : 6
201.0
Row :  47 Col : 7
117.0
Row :  47 Col : 8
138.0
Row :  47 Col : 9
231.0
Row :  47 Col : 10
118.0
Row :  47 Col : 11
129.0
Row :  47 Col : 12
202.0
Row :  47 Col : 13
225.0
Row :  47 Col : 14
129.0
Row :  47 Col : 15
171.0
Row :  47 Col : 16
170.0
Row :  47 Col : 17
166.0
Row :  47 Col : 18
174.0
Row :  47 Col : 19
200.0
Row :  47 Col : 20
216.0
Row :  47 Col : 21
179.0
Row :  47 Col : 22
181.0
Row :  47 Col : 23
239.0
Row :  47 Col : 24
119.0
Row :  47 Col : 25
158.0
Row :  47 Col : 26
135.0
Row :  47 Col : 27
225.0
Row :  47 Col : 28
181.0
Row :  47 Col : 29
116.0
Row :  47 Col : 30
231.0
Row :  47 Col : 31
197.0
Row :  47 Col : 32
134.0
Row :  47 Col : 33
208.0
Row :  47 

Row :  50 Col : 37
159.0
Row :  50 Col : 38
133.0
Row :  50 Col : 39
103.0
Row :  50 Col : 40
137.0
Row :  50 Col : 41
232.0
Row :  50 Col : 42
144.0
Row :  50 Col : 43
106.0
Row :  50 Col : 44
235.0
Row :  50 Col : 45
228.0
Row :  50 Col : 46
175.0
Row :  50 Col : 47
150.0
Row :  50 Col : 48
236.0
Row :  50 Col : 49
160.0
Row :  50 Col : 50
101.0
Row :  50 Col : 51
237.0
Row :  50 Col : 52
198.0
Row :  50 Col : 53
102.0
Row :  50 Col : 54
229.0
Row :  50 Col : 55
217.0
Row :  50 Col : 56
140.0
Row :  50 Col : 57
194.0
Row :  50 Col : 58
115.0
Row :  50 Col : 59
220.0
Row :  50 Col : 60
169.0
Row :  50 Col : 61
175.0
Row :  50 Col : 62
192.0
Row :  50 Col : 63
217.0
Row :  50 Col : 64
198.0
Row :  50 Col : 65
124.0
Row :  50 Col : 66
215.0
Row :  50 Col : 67
232.0
Row :  50 Col : 68
235.0
Row :  50 Col : 69
124.0
Row :  50 Col : 70
236.0
Row :  50 Col : 71
179.0
Row :  50 Col : 72
225.0
Row :  50 Col : 73
171.0
Row :  50 Col : 74
121.0
Row :  50 Col : 75
103.0
Row :  50 Col : 76
123.0


Row :  57 Col : 45
128.0
Row :  57 Col : 46
198.0
Row :  57 Col : 47
196.0
Row :  57 Col : 48
132.0
Row :  57 Col : 49
140.0
Row :  57 Col : 50
185.0
Row :  57 Col : 51
109.0
Row :  57 Col : 52
220.0
Row :  57 Col : 53
177.0
Row :  57 Col : 54
105.0
Row :  57 Col : 55
103.0
Row :  57 Col : 56
235.0
Row :  57 Col : 57
237.0
Row :  57 Col : 58
132.0
Row :  57 Col : 59
233.0
Row :  57 Col : 60
106.0
Row :  57 Col : 61
166.0
Row :  57 Col : 62
204.0
Row :  57 Col : 63
154.0
Row :  57 Col : 64
161.0
Row :  57 Col : 65
105.0
Row :  57 Col : 66
172.0
Row :  57 Col : 67
150.0
Row :  57 Col : 68
112.0
Row :  57 Col : 69
154.0
Row :  57 Col : 70
199.0
Row :  57 Col : 71
198.0
Row :  57 Col : 72
240.0
Row :  57 Col : 73
132.0
Row :  57 Col : 74
166.0
Row :  57 Col : 75
137.0
Row :  57 Col : 76
235.0
Row :  57 Col : 77
202.0
Row :  57 Col : 78
172.0
Row :  57 Col : 79
123.0
Row :  57 Col : 80
189.0
Row :  57 Col : 81
197.0
Row :  57 Col : 82
178.0
Row :  57 Col : 83
195.0
Row :  57 Col : 84
134.0


115.0
Row :  62 Col : 36
154.0
Row :  62 Col : 37
236.0
Row :  62 Col : 38
142.0
Row :  62 Col : 39
178.0
Row :  62 Col : 40
172.0
Row :  62 Col : 41
168.0
Row :  62 Col : 42
182.0
Row :  62 Col : 43
103.0
Row :  62 Col : 44
221.0
Row :  62 Col : 45
239.0
Row :  62 Col : 46
235.0
Row :  62 Col : 47
186.0
Row :  62 Col : 48
107.0
Row :  62 Col : 49
230.0
Row :  62 Col : 50
129.0
Row :  62 Col : 51
201.0
Row :  62 Col : 52
111.0
Row :  62 Col : 53
127.0
Row :  62 Col : 54
101.0
Row :  62 Col : 55
128.0
Row :  62 Col : 56
185.0
Row :  62 Col : 57
118.0
Row :  62 Col : 58
103.0
Row :  62 Col : 59
175.0
Row :  62 Col : 60
217.0
Row :  62 Col : 61
141.0
Row :  62 Col : 62
211.0
Row :  62 Col : 63
144.0
Row :  62 Col : 64
125.0
Row :  62 Col : 65
167.0
Row :  62 Col : 66
115.0
Row :  62 Col : 67
213.0
Row :  62 Col : 68
173.0
Row :  62 Col : 69
167.0
Row :  62 Col : 70
136.0
Row :  62 Col : 71
228.0
Row :  62 Col : 72
136.0
Row :  62 Col : 73
149.0
Row :  62 Col : 74
223.0
Row :  62 Col : 75


Row :  66 Col : 13
234.0
Row :  66 Col : 14
174.0
Row :  66 Col : 15
180.0
Row :  66 Col : 16
104.0
Row :  66 Col : 17
163.0
Row :  66 Col : 18
201.0
Row :  66 Col : 19
223.0
Row :  66 Col : 20
183.0
Row :  66 Col : 21
227.0
Row :  66 Col : 22
214.0
Row :  66 Col : 23
184.0
Row :  66 Col : 24
163.0
Row :  66 Col : 25
106.0
Row :  66 Col : 26
226.0
Row :  66 Col : 27
159.0
Row :  66 Col : 28
101.0
Row :  66 Col : 29
110.0
Row :  66 Col : 30
137.0
Row :  66 Col : 31
190.0
Row :  66 Col : 32
226.0
Row :  66 Col : 33
111.0
Row :  66 Col : 34
201.0
Row :  66 Col : 35
106.0
Row :  66 Col : 36
157.0
Row :  66 Col : 37
180.0
Row :  66 Col : 38
153.0
Row :  66 Col : 39
160.0
Row :  66 Col : 40
236.0
Row :  66 Col : 41
131.0
Row :  66 Col : 42
228.0
Row :  66 Col : 43
118.0
Row :  66 Col : 44
103.0
Row :  66 Col : 45
113.0
Row :  66 Col : 46
156.0
Row :  66 Col : 47
156.0
Row :  66 Col : 48
159.0
Row :  66 Col : 49
167.0
Row :  66 Col : 50
237.0
Row :  66 Col : 51
203.0
Row :  66 Col : 52
201.0


Row :  70 Col : 25
164.0
Row :  70 Col : 26
236.0
Row :  70 Col : 27
204.0
Row :  70 Col : 28
134.0
Row :  70 Col : 29
113.0
Row :  70 Col : 30
218.0
Row :  70 Col : 31
100.0
Row :  70 Col : 32
110.0
Row :  70 Col : 33
153.0
Row :  70 Col : 34
109.0
Row :  70 Col : 35
193.0
Row :  70 Col : 36
109.0
Row :  70 Col : 37
186.0
Row :  70 Col : 38
236.0
Row :  70 Col : 39
133.0
Row :  70 Col : 40
142.0
Row :  70 Col : 41
192.0
Row :  70 Col : 42
172.0
Row :  70 Col : 43
236.0
Row :  70 Col : 44
160.0
Row :  70 Col : 45
222.0
Row :  70 Col : 46
109.0
Row :  70 Col : 47
180.0
Row :  70 Col : 48
123.0
Row :  70 Col : 49
116.0
Row :  70 Col : 50
140.0
Row :  70 Col : 51
173.0
Row :  70 Col : 52
180.0
Row :  70 Col : 53
200.0
Row :  70 Col : 54
126.0
Row :  70 Col : 55
168.0
Row :  70 Col : 56
214.0
Row :  70 Col : 57
172.0
Row :  70 Col : 58
183.0
Row :  70 Col : 59
168.0
Row :  70 Col : 60
215.0
Row :  70 Col : 61
238.0
Row :  70 Col : 62
176.0
Row :  70 Col : 63
110.0
Row :  70 Col : 64
239.0


Row :  74 Col : 31
110.0
Row :  74 Col : 32
174.0
Row :  74 Col : 33
133.0
Row :  74 Col : 34
179.0
Row :  74 Col : 35
177.0
Row :  74 Col : 36
171.0
Row :  74 Col : 37
101.0
Row :  74 Col : 38
130.0
Row :  74 Col : 39
229.0
Row :  74 Col : 40
208.0
Row :  74 Col : 41
109.0
Row :  74 Col : 42
192.0
Row :  74 Col : 43
232.0
Row :  74 Col : 44
118.0
Row :  74 Col : 45
207.0
Row :  74 Col : 46
182.0
Row :  74 Col : 47
191.0
Row :  74 Col : 48
109.0
Row :  74 Col : 49
132.0
Row :  74 Col : 50
235.0
Row :  74 Col : 51
198.0
Row :  74 Col : 52
181.0
Row :  74 Col : 53
214.0
Row :  74 Col : 54
229.0
Row :  74 Col : 55
194.0
Row :  74 Col : 56
154.0
Row :  74 Col : 57
232.0
Row :  74 Col : 58
175.0
Row :  74 Col : 59
121.0
Row :  74 Col : 60
107.0
Row :  74 Col : 61
229.0
Row :  74 Col : 62
179.0
Row :  74 Col : 63
220.0
Row :  74 Col : 64
138.0
Row :  74 Col : 65
183.0
Row :  74 Col : 66
110.0
Row :  74 Col : 67
127.0
Row :  74 Col : 68
170.0
Row :  74 Col : 69
216.0
Row :  74 Col : 70
172.0


Row :  79 Col : 29
161.0
Row :  79 Col : 30
128.0
Row :  79 Col : 31
144.0
Row :  79 Col : 32
102.0
Row :  79 Col : 33
184.0
Row :  79 Col : 34
182.0
Row :  79 Col : 35
105.0
Row :  79 Col : 36
187.0
Row :  79 Col : 37
192.0
Row :  79 Col : 38
222.0
Row :  79 Col : 39
128.0
Row :  79 Col : 40
182.0
Row :  79 Col : 41
204.0
Row :  79 Col : 42
192.0
Row :  79 Col : 43
161.0
Row :  79 Col : 44
240.0
Row :  79 Col : 45
153.0
Row :  79 Col : 46
152.0
Row :  79 Col : 47
193.0
Row :  79 Col : 48
172.0
Row :  79 Col : 49
228.0
Row :  79 Col : 50
168.0
Row :  79 Col : 51
212.0
Row :  79 Col : 52
154.0
Row :  79 Col : 53
119.0
Row :  79 Col : 54
199.0
Row :  79 Col : 55
189.0
Row :  79 Col : 56
121.0
Row :  79 Col : 57
205.0
Row :  79 Col : 58
210.0
Row :  79 Col : 59
216.0
Row :  79 Col : 60
212.0
Row :  79 Col : 61
109.0
Row :  79 Col : 62
238.0
Row :  79 Col : 63
116.0
Row :  79 Col : 64
226.0
Row :  79 Col : 65
186.0
Row :  79 Col : 66
227.0
Row :  79 Col : 67
144.0
Row :  79 Col : 68
105.0


212.0
Row :  86 Col : 90
177.0
Row :  86 Col : 91
161.0
Row :  86 Col : 92
190.0
Row :  86 Col : 93
200.0
Row :  86 Col : 94
220.0
Row :  86 Col : 95
141.0
Row :  86 Col : 96
115.0
Row :  86 Col : 97
211.0
Row :  86 Col : 98
233.0
Row :  86 Col : 99
134.0
Row :  87 Col : 0
161.0
Row :  87 Col : 1
217.0
Row :  87 Col : 2
161.0
Row :  87 Col : 3
107.0
Row :  87 Col : 4
115.0
Row :  87 Col : 5
219.0
Row :  87 Col : 6
235.0
Row :  87 Col : 7
112.0
Row :  87 Col : 8
206.0
Row :  87 Col : 9
165.0
Row :  87 Col : 10
101.0
Row :  87 Col : 11
238.0
Row :  87 Col : 12
205.0
Row :  87 Col : 13
149.0
Row :  87 Col : 14
167.0
Row :  87 Col : 15
120.0
Row :  87 Col : 16
182.0
Row :  87 Col : 17
225.0
Row :  87 Col : 18
158.0
Row :  87 Col : 19
213.0
Row :  87 Col : 20
236.0
Row :  87 Col : 21
222.0
Row :  87 Col : 22
212.0
Row :  87 Col : 23
157.0
Row :  87 Col : 24
205.0
Row :  87 Col : 25
188.0
Row :  87 Col : 26
232.0
Row :  87 Col : 27
183.0
Row :  87 Col : 28
154.0
Row :  87 Col : 29
197.0
Row 

139.0
Row :  90 Col : 47
195.0
Row :  90 Col : 48
234.0
Row :  90 Col : 49
140.0
Row :  90 Col : 50
120.0
Row :  90 Col : 51
225.0
Row :  90 Col : 52
147.0
Row :  90 Col : 53
105.0
Row :  90 Col : 54
147.0
Row :  90 Col : 55
192.0
Row :  90 Col : 56
162.0
Row :  90 Col : 57
214.0
Row :  90 Col : 58
122.0
Row :  90 Col : 59
219.0
Row :  90 Col : 60
220.0
Row :  90 Col : 61
179.0
Row :  90 Col : 62
110.0
Row :  90 Col : 63
120.0
Row :  90 Col : 64
220.0
Row :  90 Col : 65
199.0
Row :  90 Col : 66
155.0
Row :  90 Col : 67
153.0
Row :  90 Col : 68
112.0
Row :  90 Col : 69
216.0
Row :  90 Col : 70
240.0
Row :  90 Col : 71
129.0
Row :  90 Col : 72
186.0
Row :  90 Col : 73
184.0
Row :  90 Col : 74
222.0
Row :  90 Col : 75
169.0
Row :  90 Col : 76
187.0
Row :  90 Col : 77
195.0
Row :  90 Col : 78
136.0
Row :  90 Col : 79
184.0
Row :  90 Col : 80
149.0
Row :  90 Col : 81
170.0
Row :  90 Col : 82
237.0
Row :  90 Col : 83
205.0
Row :  90 Col : 84
210.0
Row :  90 Col : 85
192.0
Row :  90 Col : 86


Row :  95 Col : 24
186.0
Row :  95 Col : 25
154.0
Row :  95 Col : 26
161.0
Row :  95 Col : 27
238.0
Row :  95 Col : 28
179.0
Row :  95 Col : 29
106.0
Row :  95 Col : 30
213.0
Row :  95 Col : 31
116.0
Row :  95 Col : 32
240.0
Row :  95 Col : 33
212.0
Row :  95 Col : 34
152.0
Row :  95 Col : 35
145.0
Row :  95 Col : 36
213.0
Row :  95 Col : 37
121.0
Row :  95 Col : 38
196.0
Row :  95 Col : 39
127.0
Row :  95 Col : 40
134.0
Row :  95 Col : 41
137.0
Row :  95 Col : 42
199.0
Row :  95 Col : 43
172.0
Row :  95 Col : 44
154.0
Row :  95 Col : 45
110.0
Row :  95 Col : 46
108.0
Row :  95 Col : 47
171.0
Row :  95 Col : 48
156.0
Row :  95 Col : 49
102.0
Row :  95 Col : 50
114.0
Row :  95 Col : 51
156.0
Row :  95 Col : 52
229.0
Row :  95 Col : 53
149.0
Row :  95 Col : 54
187.0
Row :  95 Col : 55
148.0
Row :  95 Col : 56
108.0
Row :  95 Col : 57
110.0
Row :  95 Col : 58
200.0
Row :  95 Col : 59
128.0
Row :  95 Col : 60
228.0
Row :  95 Col : 61
215.0
Row :  95 Col : 62
109.0
Row :  95 Col : 63
190.0


In [30]:
cv2.imshow('output', image)
cv2.waitKey()
cv2.destroyAllWindows()

In [31]:
cv2.imwrite('output.png', image)

True