In [1]:
import cv2
image = cv2.imread('./images/goldengate.jpg')

print(image)

[[[164 195 192]
  [164 195 192]
  [165 196 193]
  ...
  [ 35  21  33]
  [ 35  21  33]
  [ 34  20  32]]

 [[164 195 192]
  [165 196 193]
  [165 196 193]
  ...
  [ 35  21  33]
  [ 35  21  33]
  [ 34  20  32]]

 [[164 195 194]
  [165 196 195]
  [165 196 195]
  ...
  [ 35  21  33]
  [ 35  21  33]
  [ 34  20  32]]

 ...

 [[ 29  51  69]
  [ 27  49  67]
  [ 25  47  65]
  ...
  [  6  21  37]
  [  5  21  34]
  [  5  21  34]]

 [[ 28  50  68]
  [ 27  49  67]
  [ 25  47  65]
  ...
  [  5  21  34]
  [  6  22  35]
  [  4  20  33]]

 [[ 26  48  66]
  [ 25  47  65]
  [ 23  45  63]
  ...
  [  4  20  33]
  [  7  23  36]
  [  4  20  32]]]


In [2]:
#show an image
cv2.imshow('output', image)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
#color conversion

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow('output', gray)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
# Create a blank image
import numpy as np

image = np.zeros((100, 100)) # 100 rows, 100 cols
cv2.imshow('output', image)
cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
# Checking the value of each pixel

for row in range(50):
    for col in range(50):
        print("Row : ",row,"Col :", col)
        print(image[row][col])


Row :  0 Col : 0
0.0
Row :  0 Col : 1
0.0
Row :  0 Col : 2
0.0
Row :  0 Col : 3
0.0
Row :  0 Col : 4
0.0
Row :  0 Col : 5
0.0
Row :  0 Col : 6
0.0
Row :  0 Col : 7
0.0
Row :  0 Col : 8
0.0
Row :  0 Col : 9
0.0
Row :  0 Col : 10
0.0
Row :  0 Col : 11
0.0
Row :  0 Col : 12
0.0
Row :  0 Col : 13
0.0
Row :  0 Col : 14
0.0
Row :  0 Col : 15
0.0
Row :  0 Col : 16
0.0
Row :  0 Col : 17
0.0
Row :  0 Col : 18
0.0
Row :  0 Col : 19
0.0
Row :  0 Col : 20
0.0
Row :  0 Col : 21
0.0
Row :  0 Col : 22
0.0
Row :  0 Col : 23
0.0
Row :  0 Col : 24
0.0
Row :  0 Col : 25
0.0
Row :  0 Col : 26
0.0
Row :  0 Col : 27
0.0
Row :  0 Col : 28
0.0
Row :  0 Col : 29
0.0
Row :  0 Col : 30
0.0
Row :  0 Col : 31
0.0
Row :  0 Col : 32
0.0
Row :  0 Col : 33
0.0
Row :  0 Col : 34
0.0
Row :  0 Col : 35
0.0
Row :  0 Col : 36
0.0
Row :  0 Col : 37
0.0
Row :  0 Col : 38
0.0
Row :  0 Col : 39
0.0
Row :  0 Col : 40
0.0
Row :  0 Col : 41
0.0
Row :  0 Col : 42
0.0
Row :  0 Col : 43
0.0
Row :  0 Col : 44
0.0
Row :  0 Col : 45
0.

0.0
Row :  11 Col : 24
0.0
Row :  11 Col : 25
0.0
Row :  11 Col : 26
0.0
Row :  11 Col : 27
0.0
Row :  11 Col : 28
0.0
Row :  11 Col : 29
0.0
Row :  11 Col : 30
0.0
Row :  11 Col : 31
0.0
Row :  11 Col : 32
0.0
Row :  11 Col : 33
0.0
Row :  11 Col : 34
0.0
Row :  11 Col : 35
0.0
Row :  11 Col : 36
0.0
Row :  11 Col : 37
0.0
Row :  11 Col : 38
0.0
Row :  11 Col : 39
0.0
Row :  11 Col : 40
0.0
Row :  11 Col : 41
0.0
Row :  11 Col : 42
0.0
Row :  11 Col : 43
0.0
Row :  11 Col : 44
0.0
Row :  11 Col : 45
0.0
Row :  11 Col : 46
0.0
Row :  11 Col : 47
0.0
Row :  11 Col : 48
0.0
Row :  11 Col : 49
0.0
Row :  12 Col : 0
0.0
Row :  12 Col : 1
0.0
Row :  12 Col : 2
0.0
Row :  12 Col : 3
0.0
Row :  12 Col : 4
0.0
Row :  12 Col : 5
0.0
Row :  12 Col : 6
0.0
Row :  12 Col : 7
0.0
Row :  12 Col : 8
0.0
Row :  12 Col : 9
0.0
Row :  12 Col : 10
0.0
Row :  12 Col : 11
0.0
Row :  12 Col : 12
0.0
Row :  12 Col : 13
0.0
Row :  12 Col : 14
0.0
Row :  12 Col : 15
0.0
Row :  12 Col : 16
0.0
Row :  12 Col : 1

Row :  21 Col : 12
0.0
Row :  21 Col : 13
0.0
Row :  21 Col : 14
0.0
Row :  21 Col : 15
0.0
Row :  21 Col : 16
0.0
Row :  21 Col : 17
0.0
Row :  21 Col : 18
0.0
Row :  21 Col : 19
0.0
Row :  21 Col : 20
0.0
Row :  21 Col : 21
0.0
Row :  21 Col : 22
0.0
Row :  21 Col : 23
0.0
Row :  21 Col : 24
0.0
Row :  21 Col : 25
0.0
Row :  21 Col : 26
0.0
Row :  21 Col : 27
0.0
Row :  21 Col : 28
0.0
Row :  21 Col : 29
0.0
Row :  21 Col : 30
0.0
Row :  21 Col : 31
0.0
Row :  21 Col : 32
0.0
Row :  21 Col : 33
0.0
Row :  21 Col : 34
0.0
Row :  21 Col : 35
0.0
Row :  21 Col : 36
0.0
Row :  21 Col : 37
0.0
Row :  21 Col : 38
0.0
Row :  21 Col : 39
0.0
Row :  21 Col : 40
0.0
Row :  21 Col : 41
0.0
Row :  21 Col : 42
0.0
Row :  21 Col : 43
0.0
Row :  21 Col : 44
0.0
Row :  21 Col : 45
0.0
Row :  21 Col : 46
0.0
Row :  21 Col : 47
0.0
Row :  21 Col : 48
0.0
Row :  21 Col : 49
0.0
Row :  22 Col : 0
0.0
Row :  22 Col : 1
0.0
Row :  22 Col : 2
0.0
Row :  22 Col : 3
0.0
Row :  22 Col : 4
0.0
Row :  22 Col : 

0.0
Row :  30 Col : 40
0.0
Row :  30 Col : 41
0.0
Row :  30 Col : 42
0.0
Row :  30 Col : 43
0.0
Row :  30 Col : 44
0.0
Row :  30 Col : 45
0.0
Row :  30 Col : 46
0.0
Row :  30 Col : 47
0.0
Row :  30 Col : 48
0.0
Row :  30 Col : 49
0.0
Row :  31 Col : 0
0.0
Row :  31 Col : 1
0.0
Row :  31 Col : 2
0.0
Row :  31 Col : 3
0.0
Row :  31 Col : 4
0.0
Row :  31 Col : 5
0.0
Row :  31 Col : 6
0.0
Row :  31 Col : 7
0.0
Row :  31 Col : 8
0.0
Row :  31 Col : 9
0.0
Row :  31 Col : 10
0.0
Row :  31 Col : 11
0.0
Row :  31 Col : 12
0.0
Row :  31 Col : 13
0.0
Row :  31 Col : 14
0.0
Row :  31 Col : 15
0.0
Row :  31 Col : 16
0.0
Row :  31 Col : 17
0.0
Row :  31 Col : 18
0.0
Row :  31 Col : 19
0.0
Row :  31 Col : 20
0.0
Row :  31 Col : 21
0.0
Row :  31 Col : 22
0.0
Row :  31 Col : 23
0.0
Row :  31 Col : 24
0.0
Row :  31 Col : 25
0.0
Row :  31 Col : 26
0.0
Row :  31 Col : 27
0.0
Row :  31 Col : 28
0.0
Row :  31 Col : 29
0.0
Row :  31 Col : 30
0.0
Row :  31 Col : 31
0.0
Row :  31 Col : 32
0.0
Row :  31 Col : 3

Row :  39 Col : 41
0.0
Row :  39 Col : 42
0.0
Row :  39 Col : 43
0.0
Row :  39 Col : 44
0.0
Row :  39 Col : 45
0.0
Row :  39 Col : 46
0.0
Row :  39 Col : 47
0.0
Row :  39 Col : 48
0.0
Row :  39 Col : 49
0.0
Row :  40 Col : 0
0.0
Row :  40 Col : 1
0.0
Row :  40 Col : 2
0.0
Row :  40 Col : 3
0.0
Row :  40 Col : 4
0.0
Row :  40 Col : 5
0.0
Row :  40 Col : 6
0.0
Row :  40 Col : 7
0.0
Row :  40 Col : 8
0.0
Row :  40 Col : 9
0.0
Row :  40 Col : 10
0.0
Row :  40 Col : 11
0.0
Row :  40 Col : 12
0.0
Row :  40 Col : 13
0.0
Row :  40 Col : 14
0.0
Row :  40 Col : 15
0.0
Row :  40 Col : 16
0.0
Row :  40 Col : 17
0.0
Row :  40 Col : 18
0.0
Row :  40 Col : 19
0.0
Row :  40 Col : 20
0.0
Row :  40 Col : 21
0.0
Row :  40 Col : 22
0.0
Row :  40 Col : 23
0.0
Row :  40 Col : 24
0.0
Row :  40 Col : 25
0.0
Row :  40 Col : 26
0.0
Row :  40 Col : 27
0.0
Row :  40 Col : 28
0.0
Row :  40 Col : 29
0.0
Row :  40 Col : 30
0.0
Row :  40 Col : 31
0.0
Row :  40 Col : 32
0.0
Row :  40 Col : 33
0.0
Row :  40 Col : 34
0.

Row :  47 Col : 44
0.0
Row :  47 Col : 45
0.0
Row :  47 Col : 46
0.0
Row :  47 Col : 47
0.0
Row :  47 Col : 48
0.0
Row :  47 Col : 49
0.0
Row :  48 Col : 0
0.0
Row :  48 Col : 1
0.0
Row :  48 Col : 2
0.0
Row :  48 Col : 3
0.0
Row :  48 Col : 4
0.0
Row :  48 Col : 5
0.0
Row :  48 Col : 6
0.0
Row :  48 Col : 7
0.0
Row :  48 Col : 8
0.0
Row :  48 Col : 9
0.0
Row :  48 Col : 10
0.0
Row :  48 Col : 11
0.0
Row :  48 Col : 12
0.0
Row :  48 Col : 13
0.0
Row :  48 Col : 14
0.0
Row :  48 Col : 15
0.0
Row :  48 Col : 16
0.0
Row :  48 Col : 17
0.0
Row :  48 Col : 18
0.0
Row :  48 Col : 19
0.0
Row :  48 Col : 20
0.0
Row :  48 Col : 21
0.0
Row :  48 Col : 22
0.0
Row :  48 Col : 23
0.0
Row :  48 Col : 24
0.0
Row :  48 Col : 25
0.0
Row :  48 Col : 26
0.0
Row :  48 Col : 27
0.0
Row :  48 Col : 28
0.0
Row :  48 Col : 29
0.0
Row :  48 Col : 30
0.0
Row :  48 Col : 31
0.0
Row :  48 Col : 32
0.0
Row :  48 Col : 33
0.0
Row :  48 Col : 34
0.0
Row :  48 Col : 35
0.0
Row :  48 Col : 36
0.0
Row :  48 Col : 37
0.

In [6]:
#changing the value of each pixel
import random

#help(random.randint)

for row in range(100):
    for col in range(100):
        print("Row : ",row,"Col :", col)
        image[row][col] = int(random.randint(100,240))
        print(image[row][col])

Row :  0 Col : 0
144.0
Row :  0 Col : 1
187.0
Row :  0 Col : 2
141.0
Row :  0 Col : 3
235.0
Row :  0 Col : 4
145.0
Row :  0 Col : 5
153.0
Row :  0 Col : 6
234.0
Row :  0 Col : 7
122.0
Row :  0 Col : 8
108.0
Row :  0 Col : 9
173.0
Row :  0 Col : 10
238.0
Row :  0 Col : 11
208.0
Row :  0 Col : 12
138.0
Row :  0 Col : 13
171.0
Row :  0 Col : 14
216.0
Row :  0 Col : 15
160.0
Row :  0 Col : 16
229.0
Row :  0 Col : 17
105.0
Row :  0 Col : 18
132.0
Row :  0 Col : 19
115.0
Row :  0 Col : 20
167.0
Row :  0 Col : 21
229.0
Row :  0 Col : 22
205.0
Row :  0 Col : 23
234.0
Row :  0 Col : 24
227.0
Row :  0 Col : 25
104.0
Row :  0 Col : 26
155.0
Row :  0 Col : 27
154.0
Row :  0 Col : 28
173.0
Row :  0 Col : 29
240.0
Row :  0 Col : 30
226.0
Row :  0 Col : 31
126.0
Row :  0 Col : 32
125.0
Row :  0 Col : 33
106.0
Row :  0 Col : 34
126.0
Row :  0 Col : 35
171.0
Row :  0 Col : 36
199.0
Row :  0 Col : 37
147.0
Row :  0 Col : 38
143.0
Row :  0 Col : 39
181.0
Row :  0 Col : 40
102.0
Row :  0 Col : 41
227.0
Ro

Row :  4 Col : 90
222.0
Row :  4 Col : 91
190.0
Row :  4 Col : 92
105.0
Row :  4 Col : 93
176.0
Row :  4 Col : 94
144.0
Row :  4 Col : 95
147.0
Row :  4 Col : 96
103.0
Row :  4 Col : 97
129.0
Row :  4 Col : 98
162.0
Row :  4 Col : 99
209.0
Row :  5 Col : 0
128.0
Row :  5 Col : 1
187.0
Row :  5 Col : 2
152.0
Row :  5 Col : 3
155.0
Row :  5 Col : 4
193.0
Row :  5 Col : 5
180.0
Row :  5 Col : 6
103.0
Row :  5 Col : 7
232.0
Row :  5 Col : 8
202.0
Row :  5 Col : 9
198.0
Row :  5 Col : 10
126.0
Row :  5 Col : 11
148.0
Row :  5 Col : 12
175.0
Row :  5 Col : 13
159.0
Row :  5 Col : 14
216.0
Row :  5 Col : 15
218.0
Row :  5 Col : 16
209.0
Row :  5 Col : 17
188.0
Row :  5 Col : 18
207.0
Row :  5 Col : 19
238.0
Row :  5 Col : 20
226.0
Row :  5 Col : 21
108.0
Row :  5 Col : 22
188.0
Row :  5 Col : 23
169.0
Row :  5 Col : 24
185.0
Row :  5 Col : 25
211.0
Row :  5 Col : 26
186.0
Row :  5 Col : 27
235.0
Row :  5 Col : 28
142.0
Row :  5 Col : 29
130.0
Row :  5 Col : 30
168.0
Row :  5 Col : 31
172.0
Ro

Row :  9 Col : 77
141.0
Row :  9 Col : 78
118.0
Row :  9 Col : 79
144.0
Row :  9 Col : 80
225.0
Row :  9 Col : 81
150.0
Row :  9 Col : 82
234.0
Row :  9 Col : 83
237.0
Row :  9 Col : 84
232.0
Row :  9 Col : 85
118.0
Row :  9 Col : 86
202.0
Row :  9 Col : 87
216.0
Row :  9 Col : 88
101.0
Row :  9 Col : 89
132.0
Row :  9 Col : 90
105.0
Row :  9 Col : 91
208.0
Row :  9 Col : 92
224.0
Row :  9 Col : 93
221.0
Row :  9 Col : 94
220.0
Row :  9 Col : 95
183.0
Row :  9 Col : 96
156.0
Row :  9 Col : 97
132.0
Row :  9 Col : 98
226.0
Row :  9 Col : 99
100.0
Row :  10 Col : 0
200.0
Row :  10 Col : 1
201.0
Row :  10 Col : 2
130.0
Row :  10 Col : 3
199.0
Row :  10 Col : 4
103.0
Row :  10 Col : 5
191.0
Row :  10 Col : 6
232.0
Row :  10 Col : 7
131.0
Row :  10 Col : 8
129.0
Row :  10 Col : 9
181.0
Row :  10 Col : 10
166.0
Row :  10 Col : 11
236.0
Row :  10 Col : 12
156.0
Row :  10 Col : 13
110.0
Row :  10 Col : 14
144.0
Row :  10 Col : 15
180.0
Row :  10 Col : 16
173.0
Row :  10 Col : 17
163.0
Row :  1

Row :  13 Col : 76
180.0
Row :  13 Col : 77
134.0
Row :  13 Col : 78
159.0
Row :  13 Col : 79
214.0
Row :  13 Col : 80
232.0
Row :  13 Col : 81
174.0
Row :  13 Col : 82
233.0
Row :  13 Col : 83
239.0
Row :  13 Col : 84
100.0
Row :  13 Col : 85
216.0
Row :  13 Col : 86
215.0
Row :  13 Col : 87
138.0
Row :  13 Col : 88
140.0
Row :  13 Col : 89
229.0
Row :  13 Col : 90
199.0
Row :  13 Col : 91
114.0
Row :  13 Col : 92
188.0
Row :  13 Col : 93
182.0
Row :  13 Col : 94
196.0
Row :  13 Col : 95
100.0
Row :  13 Col : 96
149.0
Row :  13 Col : 97
209.0
Row :  13 Col : 98
229.0
Row :  13 Col : 99
185.0
Row :  14 Col : 0
201.0
Row :  14 Col : 1
155.0
Row :  14 Col : 2
206.0
Row :  14 Col : 3
110.0
Row :  14 Col : 4
163.0
Row :  14 Col : 5
189.0
Row :  14 Col : 6
184.0
Row :  14 Col : 7
181.0
Row :  14 Col : 8
215.0
Row :  14 Col : 9
107.0
Row :  14 Col : 10
118.0
Row :  14 Col : 11
212.0
Row :  14 Col : 12
126.0
Row :  14 Col : 13
140.0
Row :  14 Col : 14
121.0
Row :  14 Col : 15
219.0
Row :  14 

176.0
Row :  17 Col : 37
179.0
Row :  17 Col : 38
215.0
Row :  17 Col : 39
113.0
Row :  17 Col : 40
233.0
Row :  17 Col : 41
209.0
Row :  17 Col : 42
184.0
Row :  17 Col : 43
228.0
Row :  17 Col : 44
160.0
Row :  17 Col : 45
168.0
Row :  17 Col : 46
226.0
Row :  17 Col : 47
140.0
Row :  17 Col : 48
120.0
Row :  17 Col : 49
197.0
Row :  17 Col : 50
184.0
Row :  17 Col : 51
114.0
Row :  17 Col : 52
148.0
Row :  17 Col : 53
104.0
Row :  17 Col : 54
181.0
Row :  17 Col : 55
139.0
Row :  17 Col : 56
116.0
Row :  17 Col : 57
198.0
Row :  17 Col : 58
223.0
Row :  17 Col : 59
208.0
Row :  17 Col : 60
114.0
Row :  17 Col : 61
138.0
Row :  17 Col : 62
121.0
Row :  17 Col : 63
132.0
Row :  17 Col : 64
187.0
Row :  17 Col : 65
186.0
Row :  17 Col : 66
143.0
Row :  17 Col : 67
156.0
Row :  17 Col : 68
129.0
Row :  17 Col : 69
156.0
Row :  17 Col : 70
240.0
Row :  17 Col : 71
216.0
Row :  17 Col : 72
199.0
Row :  17 Col : 73
185.0
Row :  17 Col : 74
233.0
Row :  17 Col : 75
201.0
Row :  17 Col : 76


Row :  22 Col : 30
116.0
Row :  22 Col : 31
161.0
Row :  22 Col : 32
221.0
Row :  22 Col : 33
125.0
Row :  22 Col : 34
108.0
Row :  22 Col : 35
161.0
Row :  22 Col : 36
224.0
Row :  22 Col : 37
206.0
Row :  22 Col : 38
180.0
Row :  22 Col : 39
170.0
Row :  22 Col : 40
105.0
Row :  22 Col : 41
133.0
Row :  22 Col : 42
187.0
Row :  22 Col : 43
108.0
Row :  22 Col : 44
105.0
Row :  22 Col : 45
202.0
Row :  22 Col : 46
115.0
Row :  22 Col : 47
120.0
Row :  22 Col : 48
112.0
Row :  22 Col : 49
102.0
Row :  22 Col : 50
173.0
Row :  22 Col : 51
194.0
Row :  22 Col : 52
113.0
Row :  22 Col : 53
181.0
Row :  22 Col : 54
114.0
Row :  22 Col : 55
227.0
Row :  22 Col : 56
100.0
Row :  22 Col : 57
240.0
Row :  22 Col : 58
165.0
Row :  22 Col : 59
138.0
Row :  22 Col : 60
110.0
Row :  22 Col : 61
136.0
Row :  22 Col : 62
239.0
Row :  22 Col : 63
214.0
Row :  22 Col : 64
128.0
Row :  22 Col : 65
187.0
Row :  22 Col : 66
171.0
Row :  22 Col : 67
224.0
Row :  22 Col : 68
162.0
Row :  22 Col : 69
226.0


Row :  26 Col : 75
160.0
Row :  26 Col : 76
160.0
Row :  26 Col : 77
133.0
Row :  26 Col : 78
152.0
Row :  26 Col : 79
109.0
Row :  26 Col : 80
126.0
Row :  26 Col : 81
159.0
Row :  26 Col : 82
203.0
Row :  26 Col : 83
192.0
Row :  26 Col : 84
169.0
Row :  26 Col : 85
162.0
Row :  26 Col : 86
104.0
Row :  26 Col : 87
193.0
Row :  26 Col : 88
109.0
Row :  26 Col : 89
127.0
Row :  26 Col : 90
156.0
Row :  26 Col : 91
142.0
Row :  26 Col : 92
184.0
Row :  26 Col : 93
169.0
Row :  26 Col : 94
148.0
Row :  26 Col : 95
139.0
Row :  26 Col : 96
156.0
Row :  26 Col : 97
104.0
Row :  26 Col : 98
156.0
Row :  26 Col : 99
166.0
Row :  27 Col : 0
219.0
Row :  27 Col : 1
120.0
Row :  27 Col : 2
151.0
Row :  27 Col : 3
223.0
Row :  27 Col : 4
208.0
Row :  27 Col : 5
182.0
Row :  27 Col : 6
111.0
Row :  27 Col : 7
114.0
Row :  27 Col : 8
237.0
Row :  27 Col : 9
218.0
Row :  27 Col : 10
128.0
Row :  27 Col : 11
150.0
Row :  27 Col : 12
143.0
Row :  27 Col : 13
100.0
Row :  27 Col : 14
197.0
Row :  27 

Row :  30 Col : 80
126.0
Row :  30 Col : 81
105.0
Row :  30 Col : 82
211.0
Row :  30 Col : 83
123.0
Row :  30 Col : 84
158.0
Row :  30 Col : 85
228.0
Row :  30 Col : 86
194.0
Row :  30 Col : 87
119.0
Row :  30 Col : 88
220.0
Row :  30 Col : 89
211.0
Row :  30 Col : 90
240.0
Row :  30 Col : 91
123.0
Row :  30 Col : 92
148.0
Row :  30 Col : 93
117.0
Row :  30 Col : 94
101.0
Row :  30 Col : 95
206.0
Row :  30 Col : 96
185.0
Row :  30 Col : 97
104.0
Row :  30 Col : 98
153.0
Row :  30 Col : 99
218.0
Row :  31 Col : 0
210.0
Row :  31 Col : 1
122.0
Row :  31 Col : 2
214.0
Row :  31 Col : 3
216.0
Row :  31 Col : 4
197.0
Row :  31 Col : 5
231.0
Row :  31 Col : 6
131.0
Row :  31 Col : 7
197.0
Row :  31 Col : 8
183.0
Row :  31 Col : 9
224.0
Row :  31 Col : 10
137.0
Row :  31 Col : 11
230.0
Row :  31 Col : 12
183.0
Row :  31 Col : 13
212.0
Row :  31 Col : 14
207.0
Row :  31 Col : 15
239.0
Row :  31 Col : 16
198.0
Row :  31 Col : 17
114.0
Row :  31 Col : 18
211.0
Row :  31 Col : 19
149.0
Row :  31 

Row :  35 Col : 88
113.0
Row :  35 Col : 89
236.0
Row :  35 Col : 90
119.0
Row :  35 Col : 91
169.0
Row :  35 Col : 92
180.0
Row :  35 Col : 93
209.0
Row :  35 Col : 94
124.0
Row :  35 Col : 95
104.0
Row :  35 Col : 96
141.0
Row :  35 Col : 97
157.0
Row :  35 Col : 98
195.0
Row :  35 Col : 99
212.0
Row :  36 Col : 0
144.0
Row :  36 Col : 1
179.0
Row :  36 Col : 2
209.0
Row :  36 Col : 3
119.0
Row :  36 Col : 4
170.0
Row :  36 Col : 5
171.0
Row :  36 Col : 6
191.0
Row :  36 Col : 7
136.0
Row :  36 Col : 8
113.0
Row :  36 Col : 9
157.0
Row :  36 Col : 10
100.0
Row :  36 Col : 11
116.0
Row :  36 Col : 12
165.0
Row :  36 Col : 13
112.0
Row :  36 Col : 14
231.0
Row :  36 Col : 15
143.0
Row :  36 Col : 16
176.0
Row :  36 Col : 17
115.0
Row :  36 Col : 18
193.0
Row :  36 Col : 19
190.0
Row :  36 Col : 20
181.0
Row :  36 Col : 21
195.0
Row :  36 Col : 22
231.0
Row :  36 Col : 23
170.0
Row :  36 Col : 24
107.0
Row :  36 Col : 25
162.0
Row :  36 Col : 26
109.0
Row :  36 Col : 27
183.0
Row :  36 

Row :  40 Col : 88
200.0
Row :  40 Col : 89
141.0
Row :  40 Col : 90
161.0
Row :  40 Col : 91
205.0
Row :  40 Col : 92
134.0
Row :  40 Col : 93
139.0
Row :  40 Col : 94
152.0
Row :  40 Col : 95
190.0
Row :  40 Col : 96
181.0
Row :  40 Col : 97
179.0
Row :  40 Col : 98
113.0
Row :  40 Col : 99
119.0
Row :  41 Col : 0
140.0
Row :  41 Col : 1
239.0
Row :  41 Col : 2
213.0
Row :  41 Col : 3
112.0
Row :  41 Col : 4
195.0
Row :  41 Col : 5
219.0
Row :  41 Col : 6
196.0
Row :  41 Col : 7
124.0
Row :  41 Col : 8
187.0
Row :  41 Col : 9
142.0
Row :  41 Col : 10
211.0
Row :  41 Col : 11
143.0
Row :  41 Col : 12
165.0
Row :  41 Col : 13
213.0
Row :  41 Col : 14
119.0
Row :  41 Col : 15
218.0
Row :  41 Col : 16
142.0
Row :  41 Col : 17
117.0
Row :  41 Col : 18
219.0
Row :  41 Col : 19
115.0
Row :  41 Col : 20
221.0
Row :  41 Col : 21
225.0
Row :  41 Col : 22
211.0
Row :  41 Col : 23
193.0
Row :  41 Col : 24
236.0
Row :  41 Col : 25
239.0
Row :  41 Col : 26
231.0
Row :  41 Col : 27
131.0
Row :  41 

Row :  45 Col : 79
171.0
Row :  45 Col : 80
110.0
Row :  45 Col : 81
107.0
Row :  45 Col : 82
138.0
Row :  45 Col : 83
217.0
Row :  45 Col : 84
219.0
Row :  45 Col : 85
161.0
Row :  45 Col : 86
228.0
Row :  45 Col : 87
155.0
Row :  45 Col : 88
155.0
Row :  45 Col : 89
141.0
Row :  45 Col : 90
194.0
Row :  45 Col : 91
127.0
Row :  45 Col : 92
216.0
Row :  45 Col : 93
232.0
Row :  45 Col : 94
221.0
Row :  45 Col : 95
187.0
Row :  45 Col : 96
236.0
Row :  45 Col : 97
180.0
Row :  45 Col : 98
236.0
Row :  45 Col : 99
204.0
Row :  46 Col : 0
132.0
Row :  46 Col : 1
151.0
Row :  46 Col : 2
227.0
Row :  46 Col : 3
129.0
Row :  46 Col : 4
122.0
Row :  46 Col : 5
213.0
Row :  46 Col : 6
150.0
Row :  46 Col : 7
142.0
Row :  46 Col : 8
131.0
Row :  46 Col : 9
216.0
Row :  46 Col : 10
133.0
Row :  46 Col : 11
213.0
Row :  46 Col : 12
196.0
Row :  46 Col : 13
198.0
Row :  46 Col : 14
175.0
Row :  46 Col : 15
235.0
Row :  46 Col : 16
197.0
Row :  46 Col : 17
225.0
Row :  46 Col : 18
240.0
Row :  46 

Row :  50 Col : 31
107.0
Row :  50 Col : 32
164.0
Row :  50 Col : 33
171.0
Row :  50 Col : 34
201.0
Row :  50 Col : 35
223.0
Row :  50 Col : 36
156.0
Row :  50 Col : 37
174.0
Row :  50 Col : 38
123.0
Row :  50 Col : 39
112.0
Row :  50 Col : 40
210.0
Row :  50 Col : 41
174.0
Row :  50 Col : 42
138.0
Row :  50 Col : 43
160.0
Row :  50 Col : 44
232.0
Row :  50 Col : 45
238.0
Row :  50 Col : 46
224.0
Row :  50 Col : 47
231.0
Row :  50 Col : 48
219.0
Row :  50 Col : 49
102.0
Row :  50 Col : 50
227.0
Row :  50 Col : 51
113.0
Row :  50 Col : 52
142.0
Row :  50 Col : 53
157.0
Row :  50 Col : 54
167.0
Row :  50 Col : 55
228.0
Row :  50 Col : 56
234.0
Row :  50 Col : 57
168.0
Row :  50 Col : 58
143.0
Row :  50 Col : 59
239.0
Row :  50 Col : 60
223.0
Row :  50 Col : 61
122.0
Row :  50 Col : 62
232.0
Row :  50 Col : 63
144.0
Row :  50 Col : 64
166.0
Row :  50 Col : 65
184.0
Row :  50 Col : 66
163.0
Row :  50 Col : 67
194.0
Row :  50 Col : 68
226.0
Row :  50 Col : 69
184.0
Row :  50 Col : 70
125.0


Row :  55 Col : 29
139.0
Row :  55 Col : 30
157.0
Row :  55 Col : 31
154.0
Row :  55 Col : 32
135.0
Row :  55 Col : 33
201.0
Row :  55 Col : 34
101.0
Row :  55 Col : 35
211.0
Row :  55 Col : 36
170.0
Row :  55 Col : 37
162.0
Row :  55 Col : 38
200.0
Row :  55 Col : 39
180.0
Row :  55 Col : 40
208.0
Row :  55 Col : 41
154.0
Row :  55 Col : 42
229.0
Row :  55 Col : 43
177.0
Row :  55 Col : 44
122.0
Row :  55 Col : 45
184.0
Row :  55 Col : 46
205.0
Row :  55 Col : 47
115.0
Row :  55 Col : 48
225.0
Row :  55 Col : 49
160.0
Row :  55 Col : 50
125.0
Row :  55 Col : 51
239.0
Row :  55 Col : 52
148.0
Row :  55 Col : 53
240.0
Row :  55 Col : 54
118.0
Row :  55 Col : 55
142.0
Row :  55 Col : 56
138.0
Row :  55 Col : 57
169.0
Row :  55 Col : 58
210.0
Row :  55 Col : 59
118.0
Row :  55 Col : 60
211.0
Row :  55 Col : 61
194.0
Row :  55 Col : 62
129.0
Row :  55 Col : 63
104.0
Row :  55 Col : 64
201.0
Row :  55 Col : 65
170.0
Row :  55 Col : 66
146.0
Row :  55 Col : 67
128.0
Row :  55 Col : 68
117.0


Row :  59 Col : 34
209.0
Row :  59 Col : 35
170.0
Row :  59 Col : 36
198.0
Row :  59 Col : 37
217.0
Row :  59 Col : 38
208.0
Row :  59 Col : 39
131.0
Row :  59 Col : 40
134.0
Row :  59 Col : 41
108.0
Row :  59 Col : 42
146.0
Row :  59 Col : 43
212.0
Row :  59 Col : 44
184.0
Row :  59 Col : 45
121.0
Row :  59 Col : 46
111.0
Row :  59 Col : 47
179.0
Row :  59 Col : 48
161.0
Row :  59 Col : 49
228.0
Row :  59 Col : 50
217.0
Row :  59 Col : 51
238.0
Row :  59 Col : 52
224.0
Row :  59 Col : 53
121.0
Row :  59 Col : 54
231.0
Row :  59 Col : 55
168.0
Row :  59 Col : 56
182.0
Row :  59 Col : 57
114.0
Row :  59 Col : 58
208.0
Row :  59 Col : 59
169.0
Row :  59 Col : 60
204.0
Row :  59 Col : 61
143.0
Row :  59 Col : 62
141.0
Row :  59 Col : 63
190.0
Row :  59 Col : 64
216.0
Row :  59 Col : 65
147.0
Row :  59 Col : 66
101.0
Row :  59 Col : 67
150.0
Row :  59 Col : 68
139.0
Row :  59 Col : 69
166.0
Row :  59 Col : 70
237.0
Row :  59 Col : 71
167.0
Row :  59 Col : 72
170.0
Row :  59 Col : 73
172.0


Row :  63 Col : 90
220.0
Row :  63 Col : 91
229.0
Row :  63 Col : 92
209.0
Row :  63 Col : 93
106.0
Row :  63 Col : 94
210.0
Row :  63 Col : 95
218.0
Row :  63 Col : 96
109.0
Row :  63 Col : 97
103.0
Row :  63 Col : 98
173.0
Row :  63 Col : 99
165.0
Row :  64 Col : 0
112.0
Row :  64 Col : 1
166.0
Row :  64 Col : 2
152.0
Row :  64 Col : 3
171.0
Row :  64 Col : 4
184.0
Row :  64 Col : 5
132.0
Row :  64 Col : 6
171.0
Row :  64 Col : 7
224.0
Row :  64 Col : 8
155.0
Row :  64 Col : 9
121.0
Row :  64 Col : 10
166.0
Row :  64 Col : 11
133.0
Row :  64 Col : 12
166.0
Row :  64 Col : 13
236.0
Row :  64 Col : 14
134.0
Row :  64 Col : 15
124.0
Row :  64 Col : 16
228.0
Row :  64 Col : 17
227.0
Row :  64 Col : 18
115.0
Row :  64 Col : 19
171.0
Row :  64 Col : 20
184.0
Row :  64 Col : 21
161.0
Row :  64 Col : 22
128.0
Row :  64 Col : 23
169.0
Row :  64 Col : 24
188.0
Row :  64 Col : 25
213.0
Row :  64 Col : 26
217.0
Row :  64 Col : 27
129.0
Row :  64 Col : 28
176.0
Row :  64 Col : 29
203.0
Row :  64 

Row :  67 Col : 49
163.0
Row :  67 Col : 50
152.0
Row :  67 Col : 51
235.0
Row :  67 Col : 52
115.0
Row :  67 Col : 53
202.0
Row :  67 Col : 54
143.0
Row :  67 Col : 55
190.0
Row :  67 Col : 56
174.0
Row :  67 Col : 57
118.0
Row :  67 Col : 58
136.0
Row :  67 Col : 59
185.0
Row :  67 Col : 60
183.0
Row :  67 Col : 61
141.0
Row :  67 Col : 62
186.0
Row :  67 Col : 63
194.0
Row :  67 Col : 64
125.0
Row :  67 Col : 65
147.0
Row :  67 Col : 66
146.0
Row :  67 Col : 67
163.0
Row :  67 Col : 68
134.0
Row :  67 Col : 69
133.0
Row :  67 Col : 70
186.0
Row :  67 Col : 71
101.0
Row :  67 Col : 72
224.0
Row :  67 Col : 73
118.0
Row :  67 Col : 74
210.0
Row :  67 Col : 75
145.0
Row :  67 Col : 76
215.0
Row :  67 Col : 77
212.0
Row :  67 Col : 78
104.0
Row :  67 Col : 79
211.0
Row :  67 Col : 80
106.0
Row :  67 Col : 81
217.0
Row :  67 Col : 82
240.0
Row :  67 Col : 83
128.0
Row :  67 Col : 84
143.0
Row :  67 Col : 85
144.0
Row :  67 Col : 86
144.0
Row :  67 Col : 87
154.0
Row :  67 Col : 88
181.0


Row :  70 Col : 82
103.0
Row :  70 Col : 83
146.0
Row :  70 Col : 84
234.0
Row :  70 Col : 85
120.0
Row :  70 Col : 86
204.0
Row :  70 Col : 87
215.0
Row :  70 Col : 88
137.0
Row :  70 Col : 89
155.0
Row :  70 Col : 90
129.0
Row :  70 Col : 91
135.0
Row :  70 Col : 92
140.0
Row :  70 Col : 93
159.0
Row :  70 Col : 94
156.0
Row :  70 Col : 95
139.0
Row :  70 Col : 96
123.0
Row :  70 Col : 97
233.0
Row :  70 Col : 98
156.0
Row :  70 Col : 99
185.0
Row :  71 Col : 0
234.0
Row :  71 Col : 1
148.0
Row :  71 Col : 2
213.0
Row :  71 Col : 3
105.0
Row :  71 Col : 4
117.0
Row :  71 Col : 5
213.0
Row :  71 Col : 6
155.0
Row :  71 Col : 7
204.0
Row :  71 Col : 8
220.0
Row :  71 Col : 9
193.0
Row :  71 Col : 10
232.0
Row :  71 Col : 11
126.0
Row :  71 Col : 12
134.0
Row :  71 Col : 13
174.0
Row :  71 Col : 14
102.0
Row :  71 Col : 15
211.0
Row :  71 Col : 16
152.0
Row :  71 Col : 17
208.0
Row :  71 Col : 18
195.0
Row :  71 Col : 19
151.0
Row :  71 Col : 20
165.0
Row :  71 Col : 21
103.0
Row :  71 

Row :  74 Col : 81
145.0
Row :  74 Col : 82
175.0
Row :  74 Col : 83
185.0
Row :  74 Col : 84
201.0
Row :  74 Col : 85
239.0
Row :  74 Col : 86
156.0
Row :  74 Col : 87
102.0
Row :  74 Col : 88
127.0
Row :  74 Col : 89
133.0
Row :  74 Col : 90
128.0
Row :  74 Col : 91
180.0
Row :  74 Col : 92
111.0
Row :  74 Col : 93
222.0
Row :  74 Col : 94
232.0
Row :  74 Col : 95
195.0
Row :  74 Col : 96
132.0
Row :  74 Col : 97
103.0
Row :  74 Col : 98
143.0
Row :  74 Col : 99
107.0
Row :  75 Col : 0
181.0
Row :  75 Col : 1
177.0
Row :  75 Col : 2
121.0
Row :  75 Col : 3
181.0
Row :  75 Col : 4
204.0
Row :  75 Col : 5
131.0
Row :  75 Col : 6
207.0
Row :  75 Col : 7
150.0
Row :  75 Col : 8
139.0
Row :  75 Col : 9
123.0
Row :  75 Col : 10
159.0
Row :  75 Col : 11
127.0
Row :  75 Col : 12
110.0
Row :  75 Col : 13
191.0
Row :  75 Col : 14
205.0
Row :  75 Col : 15
218.0
Row :  75 Col : 16
184.0
Row :  75 Col : 17
169.0
Row :  75 Col : 18
104.0
Row :  75 Col : 19
139.0
Row :  75 Col : 20
179.0
Row :  75 

171.0
Row :  78 Col : 87
204.0
Row :  78 Col : 88
114.0
Row :  78 Col : 89
216.0
Row :  78 Col : 90
156.0
Row :  78 Col : 91
192.0
Row :  78 Col : 92
177.0
Row :  78 Col : 93
144.0
Row :  78 Col : 94
129.0
Row :  78 Col : 95
170.0
Row :  78 Col : 96
208.0
Row :  78 Col : 97
224.0
Row :  78 Col : 98
179.0
Row :  78 Col : 99
170.0
Row :  79 Col : 0
113.0
Row :  79 Col : 1
201.0
Row :  79 Col : 2
125.0
Row :  79 Col : 3
236.0
Row :  79 Col : 4
156.0
Row :  79 Col : 5
126.0
Row :  79 Col : 6
122.0
Row :  79 Col : 7
235.0
Row :  79 Col : 8
204.0
Row :  79 Col : 9
147.0
Row :  79 Col : 10
213.0
Row :  79 Col : 11
227.0
Row :  79 Col : 12
160.0
Row :  79 Col : 13
188.0
Row :  79 Col : 14
238.0
Row :  79 Col : 15
164.0
Row :  79 Col : 16
160.0
Row :  79 Col : 17
236.0
Row :  79 Col : 18
186.0
Row :  79 Col : 19
152.0
Row :  79 Col : 20
166.0
Row :  79 Col : 21
131.0
Row :  79 Col : 22
116.0
Row :  79 Col : 23
157.0
Row :  79 Col : 24
207.0
Row :  79 Col : 25
103.0
Row :  79 Col : 26
203.0
Row 

Row :  82 Col : 27
129.0
Row :  82 Col : 28
104.0
Row :  82 Col : 29
218.0
Row :  82 Col : 30
226.0
Row :  82 Col : 31
159.0
Row :  82 Col : 32
135.0
Row :  82 Col : 33
115.0
Row :  82 Col : 34
115.0
Row :  82 Col : 35
189.0
Row :  82 Col : 36
129.0
Row :  82 Col : 37
170.0
Row :  82 Col : 38
189.0
Row :  82 Col : 39
112.0
Row :  82 Col : 40
160.0
Row :  82 Col : 41
145.0
Row :  82 Col : 42
204.0
Row :  82 Col : 43
113.0
Row :  82 Col : 44
166.0
Row :  82 Col : 45
210.0
Row :  82 Col : 46
215.0
Row :  82 Col : 47
158.0
Row :  82 Col : 48
146.0
Row :  82 Col : 49
129.0
Row :  82 Col : 50
207.0
Row :  82 Col : 51
114.0
Row :  82 Col : 52
178.0
Row :  82 Col : 53
228.0
Row :  82 Col : 54
208.0
Row :  82 Col : 55
117.0
Row :  82 Col : 56
103.0
Row :  82 Col : 57
223.0
Row :  82 Col : 58
102.0
Row :  82 Col : 59
155.0
Row :  82 Col : 60
177.0
Row :  82 Col : 61
214.0
Row :  82 Col : 62
169.0
Row :  82 Col : 63
201.0
Row :  82 Col : 64
209.0
Row :  82 Col : 65
161.0
Row :  82 Col : 66
200.0


Row :  86 Col : 59
240.0
Row :  86 Col : 60
204.0
Row :  86 Col : 61
189.0
Row :  86 Col : 62
223.0
Row :  86 Col : 63
104.0
Row :  86 Col : 64
122.0
Row :  86 Col : 65
141.0
Row :  86 Col : 66
224.0
Row :  86 Col : 67
208.0
Row :  86 Col : 68
147.0
Row :  86 Col : 69
230.0
Row :  86 Col : 70
228.0
Row :  86 Col : 71
225.0
Row :  86 Col : 72
235.0
Row :  86 Col : 73
139.0
Row :  86 Col : 74
131.0
Row :  86 Col : 75
217.0
Row :  86 Col : 76
228.0
Row :  86 Col : 77
159.0
Row :  86 Col : 78
194.0
Row :  86 Col : 79
231.0
Row :  86 Col : 80
174.0
Row :  86 Col : 81
221.0
Row :  86 Col : 82
101.0
Row :  86 Col : 83
106.0
Row :  86 Col : 84
165.0
Row :  86 Col : 85
182.0
Row :  86 Col : 86
115.0
Row :  86 Col : 87
142.0
Row :  86 Col : 88
134.0
Row :  86 Col : 89
233.0
Row :  86 Col : 90
173.0
Row :  86 Col : 91
102.0
Row :  86 Col : 92
220.0
Row :  86 Col : 93
104.0
Row :  86 Col : 94
225.0
Row :  86 Col : 95
148.0
Row :  86 Col : 96
175.0
Row :  86 Col : 97
145.0
Row :  86 Col : 98
238.0


Row :  90 Col : 86
187.0
Row :  90 Col : 87
120.0
Row :  90 Col : 88
130.0
Row :  90 Col : 89
140.0
Row :  90 Col : 90
137.0
Row :  90 Col : 91
191.0
Row :  90 Col : 92
150.0
Row :  90 Col : 93
172.0
Row :  90 Col : 94
100.0
Row :  90 Col : 95
178.0
Row :  90 Col : 96
165.0
Row :  90 Col : 97
139.0
Row :  90 Col : 98
132.0
Row :  90 Col : 99
114.0
Row :  91 Col : 0
208.0
Row :  91 Col : 1
226.0
Row :  91 Col : 2
186.0
Row :  91 Col : 3
173.0
Row :  91 Col : 4
206.0
Row :  91 Col : 5
233.0
Row :  91 Col : 6
193.0
Row :  91 Col : 7
111.0
Row :  91 Col : 8
198.0
Row :  91 Col : 9
164.0
Row :  91 Col : 10
151.0
Row :  91 Col : 11
120.0
Row :  91 Col : 12
219.0
Row :  91 Col : 13
194.0
Row :  91 Col : 14
173.0
Row :  91 Col : 15
108.0
Row :  91 Col : 16
154.0
Row :  91 Col : 17
157.0
Row :  91 Col : 18
215.0
Row :  91 Col : 19
104.0
Row :  91 Col : 20
139.0
Row :  91 Col : 21
144.0
Row :  91 Col : 22
144.0
Row :  91 Col : 23
138.0
Row :  91 Col : 24
162.0
Row :  91 Col : 25
179.0
Row :  91 

Row :  95 Col : 86
117.0
Row :  95 Col : 87
177.0
Row :  95 Col : 88
198.0
Row :  95 Col : 89
201.0
Row :  95 Col : 90
187.0
Row :  95 Col : 91
191.0
Row :  95 Col : 92
105.0
Row :  95 Col : 93
172.0
Row :  95 Col : 94
101.0
Row :  95 Col : 95
160.0
Row :  95 Col : 96
123.0
Row :  95 Col : 97
129.0
Row :  95 Col : 98
114.0
Row :  95 Col : 99
232.0
Row :  96 Col : 0
225.0
Row :  96 Col : 1
170.0
Row :  96 Col : 2
141.0
Row :  96 Col : 3
146.0
Row :  96 Col : 4
209.0
Row :  96 Col : 5
112.0
Row :  96 Col : 6
122.0
Row :  96 Col : 7
180.0
Row :  96 Col : 8
239.0
Row :  96 Col : 9
212.0
Row :  96 Col : 10
114.0
Row :  96 Col : 11
140.0
Row :  96 Col : 12
122.0
Row :  96 Col : 13
184.0
Row :  96 Col : 14
118.0
Row :  96 Col : 15
113.0
Row :  96 Col : 16
101.0
Row :  96 Col : 17
226.0
Row :  96 Col : 18
239.0
Row :  96 Col : 19
118.0
Row :  96 Col : 20
166.0
Row :  96 Col : 21
226.0
Row :  96 Col : 22
171.0
Row :  96 Col : 23
207.0
Row :  96 Col : 24
164.0
Row :  96 Col : 25
116.0
Row :  96 

In [7]:
cv2.imshow('output', image)
cv2.waitKey()
cv2.destroyAllWindows()

In [8]:
cv2.imwrite('output.png', image)

True